apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
spec: 
  type: NodePort
  ports:
    - port: 8080
      name: metro-bundler
      targetPort: 19000
      nodePort: 30004
    - port: 8081
      name: dev-tool
      targetPort: 19002
      nodePort: 30005
    - port: 8082
      name: web-app
      targetPort: 19006
      nodePort: 30006
  selector:
      app: frontend
    


