version: '3'
services:
    handbook:
        environment:
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
            - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.29.186 #IP Address of local machine
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
             - 19000:19000 # Specify port-forwarding
             - 19001:19001
             - 19002:19002
             - 19006:19006
